### ISSUE TITLE
Please allow me to ask you a question about your code to open the nurse dataset (file 01-extract-data-from-nurse-dataset.ipynb) 

### ISSUE THREAD

**Issue by hieutv85** [fbeierle/stress-recognition#1]
Hi,

Thank you very much for your GitHub repository.
 
With the file 01-extract-data-from-nurse-dataset.ipynb, I think you used only two types of labels for the nurse dataset, and you combined labels value 1 (low stress) and val 2 (high stress) to both value 1 since the dataset is highly imbalanced. Could you please tell me how to change your code to load the nurse dataset but still keep the three labels?
 
Thank you very much. Please support me.

**Comment by fbeierle** [comment]
Hi. The labels for the stress levels are stored in the excel file of the dataset. I was using level 0 and level 2 for my analysis. After reading the data in, you can decide how to handle it and what to keep.

In this script
https://github.com/fbeierle/stress-detection/blob/main/model-development/01-extract-data-from-nurse-dataset.ipynb

```
survey = pd.read_excel('doi_10.5061_dryad.5hqbzkh6f__v6/SurveyResults.xlsx',
                parse_dates=[['date', 'Start time'], ['date', 'End time']],
                dtype={'ID':str, 'Stress level':str})
```
loads the whole meta-data set, including all stress labels. After that, I format and drop the rows that I don't need.

**Comment by hieutv85** [comment]
Thank you very much @fbeierle.
